sudo: required
language: generic 

services:
  - docker

before install:
  - docker build -t bnuar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bnuar/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-963333996612"
  bucket_path: "docker"
  on:
    branch: master
  ACCESS_KEY_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"